# Generated by Django 4.2.18 on 2026-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_customfont'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfig',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_backgrounds/'),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='background_mode',
            field=models.CharField(choices=[('scroll_tile', '随页面滚动并平铺'), ('fixed_cover', '静止背景')], default='scroll_tile', max_length=20),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='background_opacity',
            field=models.FloatField(default=0.22),
        ),
    ]
