# Generated by Django 4.2.18 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0003_themeconfig_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorhomepageconfig",
            name="global_style",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="authorhomepageconfig",
            name="page_schema_draft",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="authorhomepageconfig",
            name="page_schema_published",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
