# Generated by Django 4.2.18 on 2026-04-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_authorhomepageconfig_page_schemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorhomepageconfig',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='author_avatars/'),
        ),
        migrations.AddField(
            model_name='authorhomepageconfig',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_headers/'),
        ),
    ]
