# Generated by Django 4.2.18 on 2026-04-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0005_authorhomepageconfig_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorhomepageconfig',
            name='author_bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
