# Generated by Django 4.2.18 on 2026-04-18 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0004_novel_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_mode', models.CharField(choices=[('open', '开放注册'), ('invite_only', '仅邀请码注册')], default='invite_only', max_length=24)),
                ('default_registration_role', models.CharField(default='author', max_length=16)),
                ('advanced_css_review_mode', models.CharField(choices=[('manual', '手动审核'), ('auto', '自动通过（高风险）')], default='manual', max_length=16)),
                ('sandbox_preset', models.CharField(default='allow-scripts allow-same-origin', max_length=128)),
                ('sensitive_words', models.TextField(blank=True)),
                ('ip_whitelist', models.TextField(blank=True)),
                ('ip_blacklist', models.TextField(blank=True)),
                ('require_public_review', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('internal', '内部公开'), ('editor', '编辑组'), ('private', '私密')], default='internal', max_length=16)),
                ('status', models.CharField(choices=[('normal', '正常'), ('reported', '被举报'), ('hidden', '已屏蔽')], default='normal', max_length=16)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roast_messages', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roast_messages', to='novels.chapter')),
                ('mentioned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in_roasts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast_messages', to='novels.novel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoastReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('roast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='adminpanel.roastmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('workspace', '作品内容'), ('homepage', '主页装修'), ('roast', '吐槽'), ('other', '其他')], default='workspace', max_length=24)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待处理'), ('ignored', '已忽略'), ('resolved', '已处理')], default='pending', max_length=16)),
                ('handle_note', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.chapter')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novels.novel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
