# Generated by Django 4.2.18 on 2026-04-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_novel_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
