# Generated by Django 4.2.18 on 2026-04-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_novel_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='character_avatars/')),
                ('role_title', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('age_label', models.CharField(blank=True, max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('relationships', models.JSONField(blank=True, default=list)),
                ('chapter_mentions', models.JSONField(blank=True, default=list)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='novels.novel')),
            ],
            options={
                'ordering': ['-is_pinned', 'sort_order', 'id'],
                'unique_together': {('novel', 'name')},
            },
        ),
    ]
