# Generated by Django 4.2.18 on 2026-04-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_novel_worldbuilding_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('content_md', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldview_entries', to='novels.novel')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('novel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorldviewLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(blank=True, max_length=255)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldview_links', to='novels.novel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='novels.worldviewentry')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='novels.worldviewentry')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
