# Generated by Django 4.2.18 on 2026-04-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_worldviewentry_plain_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldviewentry',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='worldviewlink',
            options={'ordering': ['source_id', 'target_id']},
        ),
        migrations.AlterField(
            model_name='worldviewentry',
            name='plain_content',
            field=models.TextField(blank=True),
        ),
    ]
