# Generated by Copilot on 2026-04-27

import uuid

from django.db import migrations, models


def fill_public_ids(apps, schema_editor):
    Novel = apps.get_model("novels", "Novel")
    for novel in Novel.objects.filter(public_id__isnull=True).only("id", "public_id"):
        public_id = f"wk_{uuid.uuid4().hex[:12]}"
        while Novel.objects.filter(public_id=public_id).exists():
            public_id = f"wk_{uuid.uuid4().hex[:12]}"
        novel.public_id = public_id
        novel.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0011_alter_worldviewentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="public_id",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(fill_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="novel",
            name="public_id",
            field=models.CharField(db_index=True, editable=False, max_length=16, unique=True),
        ),
    ]
